//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCN_Integration.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class FassOrder
    {
        public string OrderId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateTimeLastUpdated { get; set; }
        public string StatusLastUpdated { get; set; }
        public Nullable<System.DateTime> DateTimeCreated { get; set; }
        public Nullable<System.DateTime> DateTimeCompleted { get; set; }
        public string CustomerId { get; set; }
        public string FileNo { get; set; }
    }
}
