#region Copyright Header
// Copyright (c) 2017 Adeptive Software Corporation. All rights reserved. This
// software and documentation constitute an unpublished work and contain
// valuable trade secrets and proprietary information belonging to Adeptive
// Software Corporation (ASC). None of the foregoing material may be copied,
// duplicated or disclosed without the express written permission of ASC. ASC
// EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES CONCERNING THIS SOFTWARE AND
// DOCUMENTATION, INCLUDING ANY WARRANTIES OF MERCHANTABILITY AND/OR FITNESS
// FOR ANY PARTICULAR PURPOSE, AND WARRANTIES OF PERFORMANCE, AND ANY WARRANTY
// THAT MIGHT OTHERWISE ARISE FROM COURSE OF DEALING OR USAGE OF TRADE. NO
// WARRANTY IS EITHER EXPRESS OR IMPLIED WITH RESPECT TO THE USE OF THE
// SOFTWARE OR DOCUMENTATION. Under no circumstances shall ASC be liable for
// incidental, special, indirect, direct or consequential damages or loss of
// profits, interruption of business, or related expenses which may arise from
// use of software or documentation, including but not limited to those
// resulting from defects in software and/or documentation, or loss inaccuracy
// of data of any kind.
// 
#endregion  

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Security.Cryptography.X509Certificates;
using System.ServiceModel;
using SigningService.Models;

namespace Adeptive.ResWare.Services
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveSigningData", Namespace="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")]
    public partial class ReceiveSigningData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BilingualLanguageField;
        
        private System.Nullable<decimal> CutoffTimeField;
        
        private bool DeliveryAddressSameAsSigningField;
        
        private string DeliveryCityField;
        
        private string DeliveryStateField;
        
        private string DeliveryStreet1Field;
        
        private string DeliveryStreet2Field;
        
        private string DeliveryZipCodeField;
        
        private string FileNumberField;
        
        private bool IsCancelledField;
        
        private string LocationField;
        
        private string LocationCityField;
        
        private string LocationCompanyNameField;
        
        private string LocationCountyField;
        
        private string LocationStateField;
        
        private string LocationStreet1Field;
        
        private string LocationStreet2Field;
        
        private string LocationZIPField;
        
        private int SenderSigningNumberField;
        
        private System.Nullable<System.DateTime> SigningDateTimeField;
        
        private string SigningNameField;
        
        private Adeptive.ResWare.Services.ReceiveSigningParty[] SigningPartiesField;
        
        private System.Nullable<int> SigningTimeZoneIndexField;
        
        private System.Nullable<int> SigningTypeIDField;
        
        private string SpecialInstructionsField;
        
        private string TransacteeEmailAddressField;
        
        private string TransacteeMobilePhoneField;
        
        private string TransacteePhoneField;
        
        private string TransacteeWorkPhoneField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BilingualLanguage
        {
            get
            {
                return this.BilingualLanguageField;
            }
            set
            {
                this.BilingualLanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CutoffTime
        {
            get
            {
                return this.CutoffTimeField;
            }
            set
            {
                this.CutoffTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DeliveryAddressSameAsSigning
        {
            get
            {
                return this.DeliveryAddressSameAsSigningField;
            }
            set
            {
                this.DeliveryAddressSameAsSigningField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryCity
        {
            get
            {
                return this.DeliveryCityField;
            }
            set
            {
                this.DeliveryCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryState
        {
            get
            {
                return this.DeliveryStateField;
            }
            set
            {
                this.DeliveryStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryStreet1
        {
            get
            {
                return this.DeliveryStreet1Field;
            }
            set
            {
                this.DeliveryStreet1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryStreet2
        {
            get
            {
                return this.DeliveryStreet2Field;
            }
            set
            {
                this.DeliveryStreet2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryZipCode
        {
            get
            {
                return this.DeliveryZipCodeField;
            }
            set
            {
                this.DeliveryZipCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FileNumber
        {
            get
            {
                return this.FileNumberField;
            }
            set
            {
                this.FileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCancelled
        {
            get
            {
                return this.IsCancelledField;
            }
            set
            {
                this.IsCancelledField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationCity
        {
            get
            {
                return this.LocationCityField;
            }
            set
            {
                this.LocationCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationCompanyName
        {
            get
            {
                return this.LocationCompanyNameField;
            }
            set
            {
                this.LocationCompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationCounty
        {
            get
            {
                return this.LocationCountyField;
            }
            set
            {
                this.LocationCountyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationState
        {
            get
            {
                return this.LocationStateField;
            }
            set
            {
                this.LocationStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationStreet1
        {
            get
            {
                return this.LocationStreet1Field;
            }
            set
            {
                this.LocationStreet1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationStreet2
        {
            get
            {
                return this.LocationStreet2Field;
            }
            set
            {
                this.LocationStreet2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationZIP
        {
            get
            {
                return this.LocationZIPField;
            }
            set
            {
                this.LocationZIPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SenderSigningNumber
        {
            get
            {
                return this.SenderSigningNumberField;
            }
            set
            {
                this.SenderSigningNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SigningDateTime
        {
            get
            {
                return this.SigningDateTimeField;
            }
            set
            {
                this.SigningDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SigningName
        {
            get
            {
                return this.SigningNameField;
            }
            set
            {
                this.SigningNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Adeptive.ResWare.Services.ReceiveSigningParty[] SigningParties
        {
            get
            {
                return this.SigningPartiesField;
            }
            set
            {
                this.SigningPartiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SigningTimeZoneIndex
        {
            get
            {
                return this.SigningTimeZoneIndexField;
            }
            set
            {
                this.SigningTimeZoneIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SigningTypeID
        {
            get
            {
                return this.SigningTypeIDField;
            }
            set
            {
                this.SigningTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecialInstructions
        {
            get
            {
                return this.SpecialInstructionsField;
            }
            set
            {
                this.SpecialInstructionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransacteeEmailAddress
        {
            get
            {
                return this.TransacteeEmailAddressField;
            }
            set
            {
                this.TransacteeEmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransacteeMobilePhone
        {
            get
            {
                return this.TransacteeMobilePhoneField;
            }
            set
            {
                this.TransacteeMobilePhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransacteePhone
        {
            get
            {
                return this.TransacteePhoneField;
            }
            set
            {
                this.TransacteePhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransacteeWorkPhone
        {
            get
            {
                return this.TransacteeWorkPhoneField;
            }
            set
            {
                this.TransacteeWorkPhoneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveSigningParty", Namespace="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")]
    public partial class ReceiveSigningParty : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameField;
        
        private string PhoneField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveSigningResponse", Namespace="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")]
    public partial class ReceiveSigningResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MessageField;
        
        private System.Nullable<int> ReceiverSigningNumberField;
        
        private Adeptive.ResWare.Services.ReceiveSigningResponseCode ResponseCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ReceiverSigningNumber
        {
            get
            {
                return this.ReceiverSigningNumberField;
            }
            set
            {
                this.ReceiverSigningNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Adeptive.ResWare.Services.ReceiveSigningResponseCode ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveSigningResponseCode", Namespace="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")]
    public enum ReceiveSigningResponseCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SUCCESS = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_LOGIN = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_FILE_NUMBER = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOWN_FOR_MAINTENANCE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNEXPECTED_ERROR = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SIGNING_ERROR = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SIGNING_PARTY_ERROR = 6,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.ReceiveSigningService.IReceiveSigningService")]
public interface IReceiveSigningService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiveSigningService/ReceiveSigning", ReplyAction="http://tempuri.org/IReceiveSigningService/ReceiveSigningResponse")]
    Adeptive.ResWare.Services.ReceiveSigningResponse ReceiveSigning(Adeptive.ResWare.Services.ReceiveSigningData SigningData);
}
