//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReswareOrderMonitorService.ReswareSigning {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveSigningData", Namespace="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")]
    [System.SerializableAttribute()]
    internal partial class ReceiveSigningData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BilingualLanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CutoffTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeliveryAddressSameAsSigningField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryStreet1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryStreet2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryZipCodeField;
        
        private string FileNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCancelledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationCompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationCountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationStreet1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationStreet2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationZIPField;
        
        private int SenderSigningNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SigningDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SigningNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReswareOrderMonitorService.ReswareSigning.ReceiveSigningParty[] SigningPartiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SigningTimeZoneIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SigningTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecialInstructionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransacteeEmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransacteeMobilePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransacteePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransacteeWorkPhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string BilingualLanguage {
            get {
                return this.BilingualLanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.BilingualLanguageField, value) != true)) {
                    this.BilingualLanguageField = value;
                    this.RaisePropertyChanged("BilingualLanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<decimal> CutoffTime {
            get {
                return this.CutoffTimeField;
            }
            set {
                if ((this.CutoffTimeField.Equals(value) != true)) {
                    this.CutoffTimeField = value;
                    this.RaisePropertyChanged("CutoffTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool DeliveryAddressSameAsSigning {
            get {
                return this.DeliveryAddressSameAsSigningField;
            }
            set {
                if ((this.DeliveryAddressSameAsSigningField.Equals(value) != true)) {
                    this.DeliveryAddressSameAsSigningField = value;
                    this.RaisePropertyChanged("DeliveryAddressSameAsSigning");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string DeliveryCity {
            get {
                return this.DeliveryCityField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryCityField, value) != true)) {
                    this.DeliveryCityField = value;
                    this.RaisePropertyChanged("DeliveryCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string DeliveryState {
            get {
                return this.DeliveryStateField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryStateField, value) != true)) {
                    this.DeliveryStateField = value;
                    this.RaisePropertyChanged("DeliveryState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string DeliveryStreet1 {
            get {
                return this.DeliveryStreet1Field;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryStreet1Field, value) != true)) {
                    this.DeliveryStreet1Field = value;
                    this.RaisePropertyChanged("DeliveryStreet1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string DeliveryStreet2 {
            get {
                return this.DeliveryStreet2Field;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryStreet2Field, value) != true)) {
                    this.DeliveryStreet2Field = value;
                    this.RaisePropertyChanged("DeliveryStreet2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string DeliveryZipCode {
            get {
                return this.DeliveryZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryZipCodeField, value) != true)) {
                    this.DeliveryZipCodeField = value;
                    this.RaisePropertyChanged("DeliveryZipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string FileNumber {
            get {
                return this.FileNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNumberField, value) != true)) {
                    this.FileNumberField = value;
                    this.RaisePropertyChanged("FileNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool IsCancelled {
            get {
                return this.IsCancelledField;
            }
            set {
                if ((this.IsCancelledField.Equals(value) != true)) {
                    this.IsCancelledField = value;
                    this.RaisePropertyChanged("IsCancelled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string LocationCity {
            get {
                return this.LocationCityField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationCityField, value) != true)) {
                    this.LocationCityField = value;
                    this.RaisePropertyChanged("LocationCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string LocationCompanyName {
            get {
                return this.LocationCompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationCompanyNameField, value) != true)) {
                    this.LocationCompanyNameField = value;
                    this.RaisePropertyChanged("LocationCompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string LocationCounty {
            get {
                return this.LocationCountyField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationCountyField, value) != true)) {
                    this.LocationCountyField = value;
                    this.RaisePropertyChanged("LocationCounty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string LocationState {
            get {
                return this.LocationStateField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationStateField, value) != true)) {
                    this.LocationStateField = value;
                    this.RaisePropertyChanged("LocationState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string LocationStreet1 {
            get {
                return this.LocationStreet1Field;
            }
            set {
                if ((object.ReferenceEquals(this.LocationStreet1Field, value) != true)) {
                    this.LocationStreet1Field = value;
                    this.RaisePropertyChanged("LocationStreet1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string LocationStreet2 {
            get {
                return this.LocationStreet2Field;
            }
            set {
                if ((object.ReferenceEquals(this.LocationStreet2Field, value) != true)) {
                    this.LocationStreet2Field = value;
                    this.RaisePropertyChanged("LocationStreet2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string LocationZIP {
            get {
                return this.LocationZIPField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationZIPField, value) != true)) {
                    this.LocationZIPField = value;
                    this.RaisePropertyChanged("LocationZIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal int SenderSigningNumber {
            get {
                return this.SenderSigningNumberField;
            }
            set {
                if ((this.SenderSigningNumberField.Equals(value) != true)) {
                    this.SenderSigningNumberField = value;
                    this.RaisePropertyChanged("SenderSigningNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.DateTime> SigningDateTime {
            get {
                return this.SigningDateTimeField;
            }
            set {
                if ((this.SigningDateTimeField.Equals(value) != true)) {
                    this.SigningDateTimeField = value;
                    this.RaisePropertyChanged("SigningDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string SigningName {
            get {
                return this.SigningNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SigningNameField, value) != true)) {
                    this.SigningNameField = value;
                    this.RaisePropertyChanged("SigningName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal ReswareOrderMonitorService.ReswareSigning.ReceiveSigningParty[] SigningParties {
            get {
                return this.SigningPartiesField;
            }
            set {
                if ((object.ReferenceEquals(this.SigningPartiesField, value) != true)) {
                    this.SigningPartiesField = value;
                    this.RaisePropertyChanged("SigningParties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> SigningTimeZoneIndex {
            get {
                return this.SigningTimeZoneIndexField;
            }
            set {
                if ((this.SigningTimeZoneIndexField.Equals(value) != true)) {
                    this.SigningTimeZoneIndexField = value;
                    this.RaisePropertyChanged("SigningTimeZoneIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> SigningTypeID {
            get {
                return this.SigningTypeIDField;
            }
            set {
                if ((this.SigningTypeIDField.Equals(value) != true)) {
                    this.SigningTypeIDField = value;
                    this.RaisePropertyChanged("SigningTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string SpecialInstructions {
            get {
                return this.SpecialInstructionsField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecialInstructionsField, value) != true)) {
                    this.SpecialInstructionsField = value;
                    this.RaisePropertyChanged("SpecialInstructions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string TransacteeEmailAddress {
            get {
                return this.TransacteeEmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.TransacteeEmailAddressField, value) != true)) {
                    this.TransacteeEmailAddressField = value;
                    this.RaisePropertyChanged("TransacteeEmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string TransacteeMobilePhone {
            get {
                return this.TransacteeMobilePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TransacteeMobilePhoneField, value) != true)) {
                    this.TransacteeMobilePhoneField = value;
                    this.RaisePropertyChanged("TransacteeMobilePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string TransacteePhone {
            get {
                return this.TransacteePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TransacteePhoneField, value) != true)) {
                    this.TransacteePhoneField = value;
                    this.RaisePropertyChanged("TransacteePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string TransacteeWorkPhone {
            get {
                return this.TransacteeWorkPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TransacteeWorkPhoneField, value) != true)) {
                    this.TransacteeWorkPhoneField = value;
                    this.RaisePropertyChanged("TransacteeWorkPhone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveSigningParty", Namespace="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")]
    [System.SerializableAttribute()]
    internal partial class ReceiveSigningParty : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveSigningResponse", Namespace="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")]
    [System.SerializableAttribute()]
    internal partial class ReceiveSigningResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ReceiverSigningNumberField;
        
        private ReswareOrderMonitorService.ReswareSigning.ReceiveSigningResponseCode ResponseCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<int> ReceiverSigningNumber {
            get {
                return this.ReceiverSigningNumberField;
            }
            set {
                if ((this.ReceiverSigningNumberField.Equals(value) != true)) {
                    this.ReceiverSigningNumberField = value;
                    this.RaisePropertyChanged("ReceiverSigningNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal ReswareOrderMonitorService.ReswareSigning.ReceiveSigningResponseCode ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveSigningResponseCode", Namespace="http://schemas.datacontract.org/2004/07/Adeptive.ResWare.Services")]
    internal enum ReceiveSigningResponseCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SUCCESS = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_LOGIN = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INVALID_FILE_NUMBER = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOWN_FOR_MAINTENANCE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNEXPECTED_ERROR = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SIGNING_ERROR = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SIGNING_PARTY_ERROR = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SigningServiceResult", Namespace="http://schemas.datacontract.org/2004/07/SigningService.Models")]
    [System.SerializableAttribute()]
    internal partial class SigningServiceResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClosingAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClosingCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClosingCountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ClosingDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClosingLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClosingStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClosingZipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobilePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReswareOrderMonitorService.ReswareSigning.SigningPartyServiceResult[] SigningPartiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkPhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ClosingAddress {
            get {
                return this.ClosingAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ClosingAddressField, value) != true)) {
                    this.ClosingAddressField = value;
                    this.RaisePropertyChanged("ClosingAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ClosingCity {
            get {
                return this.ClosingCityField;
            }
            set {
                if ((object.ReferenceEquals(this.ClosingCityField, value) != true)) {
                    this.ClosingCityField = value;
                    this.RaisePropertyChanged("ClosingCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ClosingCounty {
            get {
                return this.ClosingCountyField;
            }
            set {
                if ((object.ReferenceEquals(this.ClosingCountyField, value) != true)) {
                    this.ClosingCountyField = value;
                    this.RaisePropertyChanged("ClosingCounty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.DateTime> ClosingDateTime {
            get {
                return this.ClosingDateTimeField;
            }
            set {
                if ((this.ClosingDateTimeField.Equals(value) != true)) {
                    this.ClosingDateTimeField = value;
                    this.RaisePropertyChanged("ClosingDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ClosingLocation {
            get {
                return this.ClosingLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.ClosingLocationField, value) != true)) {
                    this.ClosingLocationField = value;
                    this.RaisePropertyChanged("ClosingLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ClosingState {
            get {
                return this.ClosingStateField;
            }
            set {
                if ((object.ReferenceEquals(this.ClosingStateField, value) != true)) {
                    this.ClosingStateField = value;
                    this.RaisePropertyChanged("ClosingState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ClosingZip {
            get {
                return this.ClosingZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ClosingZipField, value) != true)) {
                    this.ClosingZipField = value;
                    this.RaisePropertyChanged("ClosingZip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime CreatedDateTime {
            get {
                return this.CreatedDateTimeField;
            }
            set {
                if ((this.CreatedDateTimeField.Equals(value) != true)) {
                    this.CreatedDateTimeField = value;
                    this.RaisePropertyChanged("CreatedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string FileNumber {
            get {
                return this.FileNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNumberField, value) != true)) {
                    this.FileNumberField = value;
                    this.RaisePropertyChanged("FileNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string HomePhone {
            get {
                return this.HomePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.HomePhoneField, value) != true)) {
                    this.HomePhoneField = value;
                    this.RaisePropertyChanged("HomePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string MobilePhone {
            get {
                return this.MobilePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.MobilePhoneField, value) != true)) {
                    this.MobilePhoneField = value;
                    this.RaisePropertyChanged("MobilePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal ReswareOrderMonitorService.ReswareSigning.SigningPartyServiceResult[] SigningParties {
            get {
                return this.SigningPartiesField;
            }
            set {
                if ((object.ReferenceEquals(this.SigningPartiesField, value) != true)) {
                    this.SigningPartiesField = value;
                    this.RaisePropertyChanged("SigningParties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string WorkPhone {
            get {
                return this.WorkPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkPhoneField, value) != true)) {
                    this.WorkPhoneField = value;
                    this.RaisePropertyChanged("WorkPhone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SigningPartyServiceResult", Namespace="http://schemas.datacontract.org/2004/07/SigningService.Models")]
    [System.SerializableAttribute()]
    internal partial class SigningPartyServiceResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SigningIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Guid SigningId {
            get {
                return this.SigningIdField;
            }
            set {
                if ((this.SigningIdField.Equals(value) != true)) {
                    this.SigningIdField = value;
                    this.RaisePropertyChanged("SigningId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReswareSigning.IReceiveSigningService")]
    internal interface IReceiveSigningService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiveSigningService/ReceiveSigning", ReplyAction="http://tempuri.org/IReceiveSigningService/ReceiveSigningResponse")]
        ReswareOrderMonitorService.ReswareSigning.ReceiveSigningResponse ReceiveSigning(ReswareOrderMonitorService.ReswareSigning.ReceiveSigningData SigningData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiveSigningService/ReceiveSigning", ReplyAction="http://tempuri.org/IReceiveSigningService/ReceiveSigningResponse")]
        System.Threading.Tasks.Task<ReswareOrderMonitorService.ReswareSigning.ReceiveSigningResponse> ReceiveSigningAsync(ReswareOrderMonitorService.ReswareSigning.ReceiveSigningData SigningData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiveSigningService/GetAllSignings", ReplyAction="http://tempuri.org/IReceiveSigningService/GetAllSigningsResponse")]
        ReswareOrderMonitorService.ReswareSigning.SigningServiceResult[] GetAllSignings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiveSigningService/GetAllSignings", ReplyAction="http://tempuri.org/IReceiveSigningService/GetAllSigningsResponse")]
        System.Threading.Tasks.Task<ReswareOrderMonitorService.ReswareSigning.SigningServiceResult[]> GetAllSigningsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiveSigningService/GetSigningById", ReplyAction="http://tempuri.org/IReceiveSigningService/GetSigningByIdResponse")]
        ReswareOrderMonitorService.ReswareSigning.SigningServiceResult GetSigningById(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiveSigningService/GetSigningById", ReplyAction="http://tempuri.org/IReceiveSigningService/GetSigningByIdResponse")]
        System.Threading.Tasks.Task<ReswareOrderMonitorService.ReswareSigning.SigningServiceResult> GetSigningByIdAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiveSigningService/DeleteSigningById", ReplyAction="http://tempuri.org/IReceiveSigningService/DeleteSigningByIdResponse")]
        int DeleteSigningById(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiveSigningService/DeleteSigningById", ReplyAction="http://tempuri.org/IReceiveSigningService/DeleteSigningByIdResponse")]
        System.Threading.Tasks.Task<int> DeleteSigningByIdAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiveSigningService/UpdateSigning", ReplyAction="http://tempuri.org/IReceiveSigningService/UpdateSigningResponse")]
        int UpdateSigning(ReswareOrderMonitorService.ReswareSigning.SigningServiceResult signingPartyResult);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReceiveSigningService/UpdateSigning", ReplyAction="http://tempuri.org/IReceiveSigningService/UpdateSigningResponse")]
        System.Threading.Tasks.Task<int> UpdateSigningAsync(ReswareOrderMonitorService.ReswareSigning.SigningServiceResult signingPartyResult);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IReceiveSigningServiceChannel : ReswareOrderMonitorService.ReswareSigning.IReceiveSigningService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class ReceiveSigningServiceClient : System.ServiceModel.ClientBase<ReswareOrderMonitorService.ReswareSigning.IReceiveSigningService>, ReswareOrderMonitorService.ReswareSigning.IReceiveSigningService {
        
        public ReceiveSigningServiceClient() {
        }
        
        public ReceiveSigningServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReceiveSigningServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiveSigningServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiveSigningServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ReswareOrderMonitorService.ReswareSigning.ReceiveSigningResponse ReceiveSigning(ReswareOrderMonitorService.ReswareSigning.ReceiveSigningData SigningData) {
            return base.Channel.ReceiveSigning(SigningData);
        }
        
        public System.Threading.Tasks.Task<ReswareOrderMonitorService.ReswareSigning.ReceiveSigningResponse> ReceiveSigningAsync(ReswareOrderMonitorService.ReswareSigning.ReceiveSigningData SigningData) {
            return base.Channel.ReceiveSigningAsync(SigningData);
        }
        
        public ReswareOrderMonitorService.ReswareSigning.SigningServiceResult[] GetAllSignings() {
            return base.Channel.GetAllSignings();
        }
        
        public System.Threading.Tasks.Task<ReswareOrderMonitorService.ReswareSigning.SigningServiceResult[]> GetAllSigningsAsync() {
            return base.Channel.GetAllSigningsAsync();
        }
        
        public ReswareOrderMonitorService.ReswareSigning.SigningServiceResult GetSigningById(System.Guid id) {
            return base.Channel.GetSigningById(id);
        }
        
        public System.Threading.Tasks.Task<ReswareOrderMonitorService.ReswareSigning.SigningServiceResult> GetSigningByIdAsync(System.Guid id) {
            return base.Channel.GetSigningByIdAsync(id);
        }
        
        public int DeleteSigningById(System.Guid id) {
            return base.Channel.DeleteSigningById(id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteSigningByIdAsync(System.Guid id) {
            return base.Channel.DeleteSigningByIdAsync(id);
        }
        
        public int UpdateSigning(ReswareOrderMonitorService.ReswareSigning.SigningServiceResult signingPartyResult) {
            return base.Channel.UpdateSigning(signingPartyResult);
        }
        
        public System.Threading.Tasks.Task<int> UpdateSigningAsync(ReswareOrderMonitorService.ReswareSigning.SigningServiceResult signingPartyResult) {
            return base.Channel.UpdateSigningAsync(signingPartyResult);
        }
    }
}
