//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReswareOrderMonitorService.ReswareOrders {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderPlacementService.Address", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReswareOrderMonitorService.ReswareOrders.OrderPlacementServicePropertyAddress))]
    internal partial class OrderPlacementServiceAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressStreetInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LegalDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParcelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParcelID2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParcelID3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParcelID4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReswareOrderMonitorService.ReswareOrders.PlattedProperty[] PlattedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetDirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetSuffixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReswareOrderMonitorService.ReswareOrders.UnplattedProperty[] UnplattedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string AddressStreetInfo {
            get {
                return this.AddressStreetInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressStreetInfoField, value) != true)) {
                    this.AddressStreetInfoField = value;
                    this.RaisePropertyChanged("AddressStreetInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string LegalDescription {
            get {
                return this.LegalDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.LegalDescriptionField, value) != true)) {
                    this.LegalDescriptionField = value;
                    this.RaisePropertyChanged("LegalDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ParcelID {
            get {
                return this.ParcelIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ParcelIDField, value) != true)) {
                    this.ParcelIDField = value;
                    this.RaisePropertyChanged("ParcelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ParcelID2 {
            get {
                return this.ParcelID2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ParcelID2Field, value) != true)) {
                    this.ParcelID2Field = value;
                    this.RaisePropertyChanged("ParcelID2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ParcelID3 {
            get {
                return this.ParcelID3Field;
            }
            set {
                if ((object.ReferenceEquals(this.ParcelID3Field, value) != true)) {
                    this.ParcelID3Field = value;
                    this.RaisePropertyChanged("ParcelID3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ParcelID4 {
            get {
                return this.ParcelID4Field;
            }
            set {
                if ((object.ReferenceEquals(this.ParcelID4Field, value) != true)) {
                    this.ParcelID4Field = value;
                    this.RaisePropertyChanged("ParcelID4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal ReswareOrderMonitorService.ReswareOrders.PlattedProperty[] Platted {
            get {
                return this.PlattedField;
            }
            set {
                if ((object.ReferenceEquals(this.PlattedField, value) != true)) {
                    this.PlattedField = value;
                    this.RaisePropertyChanged("Platted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string StreetDirection {
            get {
                return this.StreetDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetDirectionField, value) != true)) {
                    this.StreetDirectionField = value;
                    this.RaisePropertyChanged("StreetDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string StreetName {
            get {
                return this.StreetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetNameField, value) != true)) {
                    this.StreetNameField = value;
                    this.RaisePropertyChanged("StreetName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string StreetNumber {
            get {
                return this.StreetNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetNumberField, value) != true)) {
                    this.StreetNumberField = value;
                    this.RaisePropertyChanged("StreetNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string StreetSuffix {
            get {
                return this.StreetSuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetSuffixField, value) != true)) {
                    this.StreetSuffixField = value;
                    this.RaisePropertyChanged("StreetSuffix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal ReswareOrderMonitorService.ReswareOrders.UnplattedProperty[] Unplatted {
            get {
                return this.UnplattedField;
            }
            set {
                if ((object.ReferenceEquals(this.UnplattedField, value) != true)) {
                    this.UnplattedField = value;
                    this.RaisePropertyChanged("Unplatted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderPlacementService.PropertyAddress", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    internal partial class OrderPlacementServicePropertyAddress : ReswareOrderMonitorService.ReswareOrders.OrderPlacementServiceAddress {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlattedProperty", Namespace="")]
    [System.SerializableAttribute()]
    internal partial class PlattedProperty : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BookPageSourceTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReswareOrderMonitorService.ReswareOrders.LotBlockOther[] LotBlockOtherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Book {
            get {
                return this.BookField;
            }
            set {
                if ((object.ReferenceEquals(this.BookField, value) != true)) {
                    this.BookField = value;
                    this.RaisePropertyChanged("Book");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal System.Nullable<int> BookPageSourceTypeID {
            get {
                return this.BookPageSourceTypeIDField;
            }
            set {
                if ((this.BookPageSourceTypeIDField.Equals(value) != true)) {
                    this.BookPageSourceTypeIDField = value;
                    this.RaisePropertyChanged("BookPageSourceTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal ReswareOrderMonitorService.ReswareOrders.LotBlockOther[] LotBlockOther {
            get {
                return this.LotBlockOtherField;
            }
            set {
                if ((object.ReferenceEquals(this.LotBlockOtherField, value) != true)) {
                    this.LotBlockOtherField = value;
                    this.RaisePropertyChanged("LotBlockOther");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Page {
            get {
                return this.PageField;
            }
            set {
                if ((object.ReferenceEquals(this.PageField, value) != true)) {
                    this.PageField = value;
                    this.RaisePropertyChanged("Page");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnplattedProperty", Namespace="")]
    [System.SerializableAttribute()]
    internal partial class UnplattedProperty : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RangeDirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownshipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownshipDirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Range {
            get {
                return this.RangeField;
            }
            set {
                if ((object.ReferenceEquals(this.RangeField, value) != true)) {
                    this.RangeField = value;
                    this.RaisePropertyChanged("Range");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string RangeDirection {
            get {
                return this.RangeDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.RangeDirectionField, value) != true)) {
                    this.RangeDirectionField = value;
                    this.RaisePropertyChanged("RangeDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Section {
            get {
                return this.SectionField;
            }
            set {
                if ((object.ReferenceEquals(this.SectionField, value) != true)) {
                    this.SectionField = value;
                    this.RaisePropertyChanged("Section");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Township {
            get {
                return this.TownshipField;
            }
            set {
                if ((object.ReferenceEquals(this.TownshipField, value) != true)) {
                    this.TownshipField = value;
                    this.RaisePropertyChanged("Township");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string TownshipDirection {
            get {
                return this.TownshipDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.TownshipDirectionField, value) != true)) {
                    this.TownshipDirectionField = value;
                    this.RaisePropertyChanged("TownshipDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LotBlockOther", Namespace="")]
    [System.SerializableAttribute()]
    internal partial class LotBlockOther : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtherField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Block {
            get {
                return this.BlockField;
            }
            set {
                if ((object.ReferenceEquals(this.BlockField, value) != true)) {
                    this.BlockField = value;
                    this.RaisePropertyChanged("Block");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Lot {
            get {
                return this.LotField;
            }
            set {
                if ((object.ReferenceEquals(this.LotField, value) != true)) {
                    this.LotField = value;
                    this.RaisePropertyChanged("Lot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Other {
            get {
                return this.OtherField;
            }
            set {
                if ((object.ReferenceEquals(this.OtherField, value) != true)) {
                    this.OtherField = value;
                    this.RaisePropertyChanged("Other");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderPlacementService.Partner", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    internal partial class OrderPlacementServicePartner : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReswareOrderMonitorService.ReswareOrders.OrderPlacementServiceAddress AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PartnerTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal ReswareOrderMonitorService.ReswareOrders.OrderPlacementServiceAddress Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ContactName {
            get {
                return this.ContactNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNameField, value) != true)) {
                    this.ContactNameField = value;
                    this.RaisePropertyChanged("ContactName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int PartnerTypeID {
            get {
                return this.PartnerTypeIDField;
            }
            set {
                if ((this.PartnerTypeIDField.Equals(value) != true)) {
                    this.PartnerTypeIDField = value;
                    this.RaisePropertyChanged("PartnerTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ReferenceNumber {
            get {
                return this.ReferenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceNumberField, value) != true)) {
                    this.ReferenceNumberField = value;
                    this.RaisePropertyChanged("ReferenceNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderPlacementService.BuyerSeller", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    internal partial class OrderPlacementServiceBuyerSeller : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReswareOrderMonitorService.ReswareOrders.OrderPlacementServiceAddress AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EntityTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaritalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SSNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReswareOrderMonitorService.ReswareOrders.OrderPlacementServiceBuyerSeller SpouseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuffixField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal ReswareOrderMonitorService.ReswareOrders.OrderPlacementServiceAddress Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string EntityName {
            get {
                return this.EntityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityNameField, value) != true)) {
                    this.EntityNameField = value;
                    this.RaisePropertyChanged("EntityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int EntityTypeID {
            get {
                return this.EntityTypeIDField;
            }
            set {
                if ((this.EntityTypeIDField.Equals(value) != true)) {
                    this.EntityTypeIDField = value;
                    this.RaisePropertyChanged("EntityTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string MaritalStatus {
            get {
                return this.MaritalStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.MaritalStatusField, value) != true)) {
                    this.MaritalStatusField = value;
                    this.RaisePropertyChanged("MaritalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Prefix {
            get {
                return this.PrefixField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefixField, value) != true)) {
                    this.PrefixField = value;
                    this.RaisePropertyChanged("Prefix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string SSN {
            get {
                return this.SSNField;
            }
            set {
                if ((object.ReferenceEquals(this.SSNField, value) != true)) {
                    this.SSNField = value;
                    this.RaisePropertyChanged("SSN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal ReswareOrderMonitorService.ReswareOrders.OrderPlacementServiceBuyerSeller Spouse {
            get {
                return this.SpouseField;
            }
            set {
                if ((object.ReferenceEquals(this.SpouseField, value) != true)) {
                    this.SpouseField = value;
                    this.RaisePropertyChanged("Spouse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Suffix {
            get {
                return this.SuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.SuffixField, value) != true)) {
                    this.SuffixField = value;
                    this.RaisePropertyChanged("Suffix");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderPlacementService.PriorPolicy", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    internal partial class OrderPlacementServicePriorPolicy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ConsiderationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PolicyDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PremiumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalesPriceOrLoanAmountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal decimal Consideration {
            get {
                return this.ConsiderationField;
            }
            set {
                if ((this.ConsiderationField.Equals(value) != true)) {
                    this.ConsiderationField = value;
                    this.RaisePropertyChanged("Consideration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime PolicyDate {
            get {
                return this.PolicyDateField;
            }
            set {
                if ((this.PolicyDateField.Equals(value) != true)) {
                    this.PolicyDateField = value;
                    this.RaisePropertyChanged("PolicyDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal decimal Premium {
            get {
                return this.PremiumField;
            }
            set {
                if ((this.PremiumField.Equals(value) != true)) {
                    this.PremiumField = value;
                    this.RaisePropertyChanged("Premium");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal decimal SalesPriceOrLoanAmount {
            get {
                return this.SalesPriceOrLoanAmountField;
            }
            set {
                if ((this.SalesPriceOrLoanAmountField.Equals(value) != true)) {
                    this.SalesPriceOrLoanAmountField = value;
                    this.RaisePropertyChanged("SalesPriceOrLoanAmount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderPlacementService.BuyerPayoff", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    internal partial class OrderPlacementServiceBuyerPayoff : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InterestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OriginationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrincipalBalanceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal decimal Interest {
            get {
                return this.InterestField;
            }
            set {
                if ((this.InterestField.Equals(value) != true)) {
                    this.InterestField = value;
                    this.RaisePropertyChanged("Interest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.DateTime> Origination {
            get {
                return this.OriginationField;
            }
            set {
                if ((this.OriginationField.Equals(value) != true)) {
                    this.OriginationField = value;
                    this.RaisePropertyChanged("Origination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal decimal PrincipalBalance {
            get {
                return this.PrincipalBalanceField;
            }
            set {
                if ((this.PrincipalBalanceField.Equals(value) != true)) {
                    this.PrincipalBalanceField = value;
                    this.RaisePropertyChanged("PrincipalBalance");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderPlacementService.SellerPayoff", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    internal partial class OrderPlacementServiceSellerPayoff : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InterestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OriginationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrincipalBalanceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal decimal Interest {
            get {
                return this.InterestField;
            }
            set {
                if ((this.InterestField.Equals(value) != true)) {
                    this.InterestField = value;
                    this.RaisePropertyChanged("Interest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.DateTime> Origination {
            get {
                return this.OriginationField;
            }
            set {
                if ((this.OriginationField.Equals(value) != true)) {
                    this.OriginationField = value;
                    this.RaisePropertyChanged("Origination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal decimal PrincipalBalance {
            get {
                return this.PrincipalBalanceField;
            }
            set {
                if ((this.PrincipalBalanceField.Equals(value) != true)) {
                    this.PrincipalBalanceField = value;
                    this.RaisePropertyChanged("PrincipalBalance");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlaceOrderResponse", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    internal partial class PlaceOrderResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AQUADecisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResWareFileIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResWareFileNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string AQUADecision {
            get {
                return this.AQUADecisionField;
            }
            set {
                if ((object.ReferenceEquals(this.AQUADecisionField, value) != true)) {
                    this.AQUADecisionField = value;
                    this.RaisePropertyChanged("AQUADecision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int ResWareFileID {
            get {
                return this.ResWareFileIDField;
            }
            set {
                if ((this.ResWareFileIDField.Equals(value) != true)) {
                    this.ResWareFileIDField = value;
                    this.RaisePropertyChanged("ResWareFileID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ResWareFileNumber {
            get {
                return this.ResWareFileNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ResWareFileNumberField, value) != true)) {
                    this.ResWareFileNumberField = value;
                    this.RaisePropertyChanged("ResWareFileNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderResult", Namespace="http://schemas.datacontract.org/2004/07/OrderPlacement.Models")]
    [System.SerializableAttribute()]
    internal partial class OrderResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReswareOrderMonitorService.ReswareOrders.BuyerSellerResult[] BuyersAndSellersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ClosingDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClosingStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocPrepStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LenderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReswareOrderMonitorService.ReswareOrders.PropertyAddressResult[] PropertyAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleOpinionStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal ReswareOrderMonitorService.ReswareOrders.BuyerSellerResult[] BuyersAndSellers {
            get {
                return this.BuyersAndSellersField;
            }
            set {
                if ((object.ReferenceEquals(this.BuyersAndSellersField, value) != true)) {
                    this.BuyersAndSellersField = value;
                    this.RaisePropertyChanged("BuyersAndSellers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Nullable<System.DateTime> ClosingDateTime {
            get {
                return this.ClosingDateTimeField;
            }
            set {
                if ((this.ClosingDateTimeField.Equals(value) != true)) {
                    this.ClosingDateTimeField = value;
                    this.RaisePropertyChanged("ClosingDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string ClosingStatus {
            get {
                return this.ClosingStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ClosingStatusField, value) != true)) {
                    this.ClosingStatusField = value;
                    this.RaisePropertyChanged("ClosingStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime CreatedDateTime {
            get {
                return this.CreatedDateTimeField;
            }
            set {
                if ((this.CreatedDateTimeField.Equals(value) != true)) {
                    this.CreatedDateTimeField = value;
                    this.RaisePropertyChanged("CreatedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIdField, value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string CustomerProduct {
            get {
                return this.CustomerProductField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerProductField, value) != true)) {
                    this.CustomerProductField = value;
                    this.RaisePropertyChanged("CustomerProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string DocPrepStatus {
            get {
                return this.DocPrepStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.DocPrepStatusField, value) != true)) {
                    this.DocPrepStatusField = value;
                    this.RaisePropertyChanged("DocPrepStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string FileNumber {
            get {
                return this.FileNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNumberField, value) != true)) {
                    this.FileNumberField = value;
                    this.RaisePropertyChanged("FileNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string LenderName {
            get {
                return this.LenderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LenderNameField, value) != true)) {
                    this.LenderNameField = value;
                    this.RaisePropertyChanged("LenderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal ReswareOrderMonitorService.ReswareOrders.PropertyAddressResult[] PropertyAddress {
            get {
                return this.PropertyAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyAddressField, value) != true)) {
                    this.PropertyAddressField = value;
                    this.RaisePropertyChanged("PropertyAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string TitleOpinionStatus {
            get {
                return this.TitleOpinionStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleOpinionStatusField, value) != true)) {
                    this.TitleOpinionStatusField = value;
                    this.RaisePropertyChanged("TitleOpinionStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BuyerSellerResult", Namespace="http://schemas.datacontract.org/2004/07/OrderPlacement.Models")]
    [System.SerializableAttribute()]
    internal partial class BuyerSellerResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReswareOrderMonitorService.ReswareOrders.BuyerSellerAddressResult[] AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaritalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SpouseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuffixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReswareOrderMonitorService.ReswareOrders.BuyerSellerEnum TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal ReswareOrderMonitorService.ReswareOrders.BuyerSellerAddressResult[] Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string EntityName {
            get {
                return this.EntityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityNameField, value) != true)) {
                    this.EntityNameField = value;
                    this.RaisePropertyChanged("EntityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string MaritalStatus {
            get {
                return this.MaritalStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.MaritalStatusField, value) != true)) {
                    this.MaritalStatusField = value;
                    this.RaisePropertyChanged("MaritalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Guid OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Prefix {
            get {
                return this.PrefixField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefixField, value) != true)) {
                    this.PrefixField = value;
                    this.RaisePropertyChanged("Prefix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool Spouse {
            get {
                return this.SpouseField;
            }
            set {
                if ((this.SpouseField.Equals(value) != true)) {
                    this.SpouseField = value;
                    this.RaisePropertyChanged("Spouse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Suffix {
            get {
                return this.SuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.SuffixField, value) != true)) {
                    this.SuffixField = value;
                    this.RaisePropertyChanged("Suffix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal ReswareOrderMonitorService.ReswareOrders.BuyerSellerEnum Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropertyAddressResult", Namespace="http://schemas.datacontract.org/2004/07/OrderPlacement.Models")]
    [System.SerializableAttribute()]
    internal partial class PropertyAddressResult : ReswareOrderMonitorService.ReswareOrders.AddressResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OrderIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Guid OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BuyerSellerAddressResult", Namespace="http://schemas.datacontract.org/2004/07/OrderPlacement.Models")]
    [System.SerializableAttribute()]
    internal partial class BuyerSellerAddressResult : ReswareOrderMonitorService.ReswareOrders.AddressResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid BuyerSellerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Guid BuyerSellerId {
            get {
                return this.BuyerSellerIdField;
            }
            set {
                if ((this.BuyerSellerIdField.Equals(value) != true)) {
                    this.BuyerSellerIdField = value;
                    this.RaisePropertyChanged("BuyerSellerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BuyerSellerEnum", Namespace="http://schemas.datacontract.org/2004/07/OrderPlacement.Common")]
    internal enum BuyerSellerEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Buyer = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Seller = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressResult", Namespace="http://schemas.datacontract.org/2004/07/OrderPlacement.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReswareOrderMonitorService.ReswareOrders.PropertyAddressResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReswareOrderMonitorService.ReswareOrders.BuyerSellerAddressResult))]
    internal partial class AddressResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressStreetInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetDirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetSuffixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string AddressStreetInfo {
            get {
                return this.AddressStreetInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressStreetInfoField, value) != true)) {
                    this.AddressStreetInfoField = value;
                    this.RaisePropertyChanged("AddressStreetInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string StreetDirection {
            get {
                return this.StreetDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetDirectionField, value) != true)) {
                    this.StreetDirectionField = value;
                    this.RaisePropertyChanged("StreetDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string StreetName {
            get {
                return this.StreetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetNameField, value) != true)) {
                    this.StreetNameField = value;
                    this.RaisePropertyChanged("StreetName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string StreetNumber {
            get {
                return this.StreetNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetNumberField, value) != true)) {
                    this.StreetNumberField = value;
                    this.RaisePropertyChanged("StreetNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string StreetSuffix {
            get {
                return this.StreetSuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetSuffixField, value) != true)) {
                    this.StreetSuffixField = value;
                    this.RaisePropertyChanged("StreetSuffix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReswareOrders.IOrderPlacementService")]
    internal interface IOrderPlacementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderPlacementService/PlaceOrder", ReplyAction="http://tempuri.org/IOrderPlacementService/PlaceOrderResponse")]
        ReswareOrderMonitorService.ReswareOrders.PlaceOrderResponse PlaceOrder(
                    int ClientID, 
                    int OfficeID, 
                    string FileNumber, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServicePropertyAddress PropertyAddress, 
                    int ClientsClientID, 
                    int TransactionTypeID, 
                    int ProductID, 
                    int UnderwriterID, 
                    int PrimaryContactID, 
                    System.Nullable<System.DateTime> EstimatedSettlementDate, 
                    decimal SalesPrice, 
                    decimal LoanAmount, 
                    string LoanNumber, 
                    decimal CashOut, 
                    string[] PayoffMortgagees, 
                    int[] OptionalActionGroupIDs, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServicePartner Lender, 
                    bool IsLender, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServiceBuyerSeller[] Buyers, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServiceBuyerSeller[] Sellers, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServicePartner[] AdditionalPartners, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServicePartner ClientsClient, 
                    string Notes, 
                    bool RequestAQUADecision, 
                    System.Nullable<decimal> OriginalDebtAmount, 
                    bool IsWholesaleOrder, 
                    string CPLCompany, 
                    string CPLDivision, 
                    string CPLStreet1, 
                    string CPLStreet2, 
                    string CPLCity, 
                    string CPLState, 
                    string CPLZip, 
                    string AssetNumber, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServicePriorPolicy PriorLenderPolicy, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServicePriorPolicy PriorOwnerPolicy, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServiceBuyerPayoff[] BuyerPayoffs, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServiceSellerPayoff[] SellerPayoffs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderPlacementService/PlaceOrder", ReplyAction="http://tempuri.org/IOrderPlacementService/PlaceOrderResponse")]
        System.Threading.Tasks.Task<ReswareOrderMonitorService.ReswareOrders.PlaceOrderResponse> PlaceOrderAsync(
                    int ClientID, 
                    int OfficeID, 
                    string FileNumber, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServicePropertyAddress PropertyAddress, 
                    int ClientsClientID, 
                    int TransactionTypeID, 
                    int ProductID, 
                    int UnderwriterID, 
                    int PrimaryContactID, 
                    System.Nullable<System.DateTime> EstimatedSettlementDate, 
                    decimal SalesPrice, 
                    decimal LoanAmount, 
                    string LoanNumber, 
                    decimal CashOut, 
                    string[] PayoffMortgagees, 
                    int[] OptionalActionGroupIDs, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServicePartner Lender, 
                    bool IsLender, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServiceBuyerSeller[] Buyers, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServiceBuyerSeller[] Sellers, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServicePartner[] AdditionalPartners, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServicePartner ClientsClient, 
                    string Notes, 
                    bool RequestAQUADecision, 
                    System.Nullable<decimal> OriginalDebtAmount, 
                    bool IsWholesaleOrder, 
                    string CPLCompany, 
                    string CPLDivision, 
                    string CPLStreet1, 
                    string CPLStreet2, 
                    string CPLCity, 
                    string CPLState, 
                    string CPLZip, 
                    string AssetNumber, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServicePriorPolicy PriorLenderPolicy, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServicePriorPolicy PriorOwnerPolicy, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServiceBuyerPayoff[] BuyerPayoffs, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServiceSellerPayoff[] SellerPayoffs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderPlacementService/GetAllOrders", ReplyAction="http://tempuri.org/IOrderPlacementService/GetAllOrdersResponse")]
        ReswareOrderMonitorService.ReswareOrders.OrderResult[] GetAllOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderPlacementService/GetAllOrders", ReplyAction="http://tempuri.org/IOrderPlacementService/GetAllOrdersResponse")]
        System.Threading.Tasks.Task<ReswareOrderMonitorService.ReswareOrders.OrderResult[]> GetAllOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderPlacementService/GetOrderById", ReplyAction="http://tempuri.org/IOrderPlacementService/GetOrderByIdResponse")]
        ReswareOrderMonitorService.ReswareOrders.OrderResult GetOrderById(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderPlacementService/GetOrderById", ReplyAction="http://tempuri.org/IOrderPlacementService/GetOrderByIdResponse")]
        System.Threading.Tasks.Task<ReswareOrderMonitorService.ReswareOrders.OrderResult> GetOrderByIdAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderPlacementService/DeleteOrderById", ReplyAction="http://tempuri.org/IOrderPlacementService/DeleteOrderByIdResponse")]
        int DeleteOrderById(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderPlacementService/DeleteOrderById", ReplyAction="http://tempuri.org/IOrderPlacementService/DeleteOrderByIdResponse")]
        System.Threading.Tasks.Task<int> DeleteOrderByIdAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderPlacementService/UpdateOrder", ReplyAction="http://tempuri.org/IOrderPlacementService/UpdateOrderResponse")]
        int UpdateOrder(ReswareOrderMonitorService.ReswareOrders.OrderResult orderResult);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderPlacementService/UpdateOrder", ReplyAction="http://tempuri.org/IOrderPlacementService/UpdateOrderResponse")]
        System.Threading.Tasks.Task<int> UpdateOrderAsync(ReswareOrderMonitorService.ReswareOrders.OrderResult orderResult);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IOrderPlacementServiceChannel : ReswareOrderMonitorService.ReswareOrders.IOrderPlacementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class OrderPlacementServiceClient : System.ServiceModel.ClientBase<ReswareOrderMonitorService.ReswareOrders.IOrderPlacementService>, ReswareOrderMonitorService.ReswareOrders.IOrderPlacementService {
        
        public OrderPlacementServiceClient() {
        }
        
        public OrderPlacementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderPlacementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderPlacementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderPlacementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ReswareOrderMonitorService.ReswareOrders.PlaceOrderResponse PlaceOrder(
                    int ClientID, 
                    int OfficeID, 
                    string FileNumber, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServicePropertyAddress PropertyAddress, 
                    int ClientsClientID, 
                    int TransactionTypeID, 
                    int ProductID, 
                    int UnderwriterID, 
                    int PrimaryContactID, 
                    System.Nullable<System.DateTime> EstimatedSettlementDate, 
                    decimal SalesPrice, 
                    decimal LoanAmount, 
                    string LoanNumber, 
                    decimal CashOut, 
                    string[] PayoffMortgagees, 
                    int[] OptionalActionGroupIDs, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServicePartner Lender, 
                    bool IsLender, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServiceBuyerSeller[] Buyers, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServiceBuyerSeller[] Sellers, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServicePartner[] AdditionalPartners, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServicePartner ClientsClient, 
                    string Notes, 
                    bool RequestAQUADecision, 
                    System.Nullable<decimal> OriginalDebtAmount, 
                    bool IsWholesaleOrder, 
                    string CPLCompany, 
                    string CPLDivision, 
                    string CPLStreet1, 
                    string CPLStreet2, 
                    string CPLCity, 
                    string CPLState, 
                    string CPLZip, 
                    string AssetNumber, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServicePriorPolicy PriorLenderPolicy, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServicePriorPolicy PriorOwnerPolicy, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServiceBuyerPayoff[] BuyerPayoffs, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServiceSellerPayoff[] SellerPayoffs) {
            return base.Channel.PlaceOrder(ClientID, OfficeID, FileNumber, PropertyAddress, ClientsClientID, TransactionTypeID, ProductID, UnderwriterID, PrimaryContactID, EstimatedSettlementDate, SalesPrice, LoanAmount, LoanNumber, CashOut, PayoffMortgagees, OptionalActionGroupIDs, Lender, IsLender, Buyers, Sellers, AdditionalPartners, ClientsClient, Notes, RequestAQUADecision, OriginalDebtAmount, IsWholesaleOrder, CPLCompany, CPLDivision, CPLStreet1, CPLStreet2, CPLCity, CPLState, CPLZip, AssetNumber, PriorLenderPolicy, PriorOwnerPolicy, BuyerPayoffs, SellerPayoffs);
        }
        
        public System.Threading.Tasks.Task<ReswareOrderMonitorService.ReswareOrders.PlaceOrderResponse> PlaceOrderAsync(
                    int ClientID, 
                    int OfficeID, 
                    string FileNumber, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServicePropertyAddress PropertyAddress, 
                    int ClientsClientID, 
                    int TransactionTypeID, 
                    int ProductID, 
                    int UnderwriterID, 
                    int PrimaryContactID, 
                    System.Nullable<System.DateTime> EstimatedSettlementDate, 
                    decimal SalesPrice, 
                    decimal LoanAmount, 
                    string LoanNumber, 
                    decimal CashOut, 
                    string[] PayoffMortgagees, 
                    int[] OptionalActionGroupIDs, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServicePartner Lender, 
                    bool IsLender, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServiceBuyerSeller[] Buyers, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServiceBuyerSeller[] Sellers, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServicePartner[] AdditionalPartners, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServicePartner ClientsClient, 
                    string Notes, 
                    bool RequestAQUADecision, 
                    System.Nullable<decimal> OriginalDebtAmount, 
                    bool IsWholesaleOrder, 
                    string CPLCompany, 
                    string CPLDivision, 
                    string CPLStreet1, 
                    string CPLStreet2, 
                    string CPLCity, 
                    string CPLState, 
                    string CPLZip, 
                    string AssetNumber, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServicePriorPolicy PriorLenderPolicy, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServicePriorPolicy PriorOwnerPolicy, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServiceBuyerPayoff[] BuyerPayoffs, 
                    ReswareOrderMonitorService.ReswareOrders.OrderPlacementServiceSellerPayoff[] SellerPayoffs) {
            return base.Channel.PlaceOrderAsync(ClientID, OfficeID, FileNumber, PropertyAddress, ClientsClientID, TransactionTypeID, ProductID, UnderwriterID, PrimaryContactID, EstimatedSettlementDate, SalesPrice, LoanAmount, LoanNumber, CashOut, PayoffMortgagees, OptionalActionGroupIDs, Lender, IsLender, Buyers, Sellers, AdditionalPartners, ClientsClient, Notes, RequestAQUADecision, OriginalDebtAmount, IsWholesaleOrder, CPLCompany, CPLDivision, CPLStreet1, CPLStreet2, CPLCity, CPLState, CPLZip, AssetNumber, PriorLenderPolicy, PriorOwnerPolicy, BuyerPayoffs, SellerPayoffs);
        }
        
        public ReswareOrderMonitorService.ReswareOrders.OrderResult[] GetAllOrders() {
            return base.Channel.GetAllOrders();
        }
        
        public System.Threading.Tasks.Task<ReswareOrderMonitorService.ReswareOrders.OrderResult[]> GetAllOrdersAsync() {
            return base.Channel.GetAllOrdersAsync();
        }
        
        public ReswareOrderMonitorService.ReswareOrders.OrderResult GetOrderById(System.Guid id) {
            return base.Channel.GetOrderById(id);
        }
        
        public System.Threading.Tasks.Task<ReswareOrderMonitorService.ReswareOrders.OrderResult> GetOrderByIdAsync(System.Guid id) {
            return base.Channel.GetOrderByIdAsync(id);
        }
        
        public int DeleteOrderById(System.Guid id) {
            return base.Channel.DeleteOrderById(id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteOrderByIdAsync(System.Guid id) {
            return base.Channel.DeleteOrderByIdAsync(id);
        }
        
        public int UpdateOrder(ReswareOrderMonitorService.ReswareOrders.OrderResult orderResult) {
            return base.Channel.UpdateOrder(orderResult);
        }
        
        public System.Threading.Tasks.Task<int> UpdateOrderAsync(ReswareOrderMonitorService.ReswareOrders.OrderResult orderResult) {
            return base.Channel.UpdateOrderAsync(orderResult);
        }
    }
}
